DS-135 : first try
makesenseorg/makesense_design-system pull request #84
Opened 2021-07-08 12:26 UTC by PaulOromi

avec option image défault + custom, description, titre et CTA

2021-07-08 13:02 UTC, MarineLB requested changes
Je t'ai mis plein plein de commentaire haha oups! 
très bon début en tout cas tu me dis si t'as besoin de clarification ou d'aide sur certains points!

2021-07-08 13:02 UTC, MarineLB commented on src/system/components/molecules/emptyState/EmptyState.vue
> +  padding-top: 1em;
Jette un oeil au spacing system 👯‍♂️ 
on évite de mettre des valeurs dans le style qui sont pas des tokens!

2021-07-08 13:02 UTC, MarineLB commented on src/system/components/molecules/emptyState/EmptyState.vue
> +<style lang="scss" scoped>
Au niveau des espacements il faudrait que tu checkes que le heading + la description on un espacement entre eux (flow) qui soit plus petit que celui entre eux + le bouton! pour le rythme visuel et l'appartenance!

2021-07-08 13:02 UTC, MarineLB commented on src/system/components/molecules/emptyState/EmptyState.vue
> +<style lang="scss" scoped>
cf l'exemple en screen de Carbon Design System sur le ticket jira !

2021-07-08 16:28 UTC, PaulOromi commented on src/system/components/molecules/emptyState/EmptyState.vue
> +        <img class="content__cover" :src="image" />
j'écris quoi dedans ? je bind une valeur ?

2021-07-09 10:41 UTC, MarineLB commented on src/system/components/molecules/emptyState/EmptyState.vue
> +      <div v-if="$slots.cta" class="content__cta mks-space-xl">
C'est top pour le slot `cta` mais pour le slot description le v-if doit être sur la div parente!

2021-07-09 10:41 UTC, MarineLB commented on src/system/components/molecules/emptyState/EmptyState.vue
> +        alt="image non affichée"
yes ici il vaut mieux binder une valeur pour permettre de contextualiser!

2021-07-09 10:41 UTC, MarineLB commented on src/system/components/molecules/emptyState/EmptyState.vue
> +      <slot name="header mks-space-xxs">
tu as mis une classe dans l'attribut name hihi! 
les classes ne sont pas affichées sur les slot parce que le tag slot est entièrement remplacé par le contenu passé dans le composant parent!

2021-07-09 11:13 UTC, MarineLB approved these changes

2021-07-09 12:07 UTC, merged